---
# update to most recent version
- name: update ansible
  hosts: localhost
  tasks:

    - git:
        repo: "https://github.com/hightekvagabond/QBSWebServer.git"
        dest: /home/ubuntu/QBSWebServer
        update: yes
        version: master
...

