---
# update to most recent version
- name: update ansible
  hosts: localhost
  tasks:

    - git:
        repo: "https://github.com/hightekvagabond/QBSWebServer.git"
        dest: /home/ubuntu/QBSWebServer
        update: yes
        version: master


    - cron:
        name: "Cronjob Entry to update nightly"
        minute: "12"
        hour: "22"
        day: "*"
        month: "*"
        weekday: "*"
        job: "/usr/bin/ansible-playbook --connection=local /home/ubuntu/QBSWebServer/ansible/update_from_git.yml"
        #become_user: "{{ admin_user }}"
      become_user: "ubuntu"
...
